version: "3.9"
services:

    #PHP Service Laravel Application
    app:
        build:
          args:
              user: ${DOCKER_USERNAME}
              uid: ${DOCKER_USER_ID}
          context: ./docker/php
          dockerfile: Dockerfile
        container_name: ${DOCKER_APP_NAME}-app
        restart: unless-stopped
        working_dir: /var/www/
        tty: true
        volumes:
          - ./:/var/www
          - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
          - ${DOCKER_APP_NAME}

    #MySQL Service
    db:
      image: mysql:8.1.0
      container_name: ${DOCKER_APP_NAME}-db
      restart: always
      environment:
          - MYSQL_DB=${DB_DATABASE}
          - MYSQL_USER=${DB_USER}
          - MYSQL_PASSWORD=${DB_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      ports:
          - ${DB_CONTAINER_PORT}:${DB_PORT}
      volumes:
        - ./docker/mysql:/var/lib/mysql
      networks:
          - ${DOCKER_APP_NAME}

    #Nginx Service
    nginx:
        image: nginx:latest
        container_name: ${DOCKER_APP_NAME}-nginx
        restart: unless-stopped
        tty: true
        ports:
          - ${DOCKER_NGINX_PORT}:80
        volumes:
          - ./:/var/www
          - ./docker/nginx:/etc/nginx/conf.d
        networks:
          - ${DOCKER_APP_NAME}

    #Supervisor
    supervisor:
        build:
            args:
                user: ${DOCKER_USERNAME}
                uid: ${DOCKER_USER_ID}
            context: ./docker/supervisor
            dockerfile: Dockerfile
        image: ${DOCKER_APP_NAME}-supervisor
        container_name: ${DOCKER_APP_NAME}-supervisor
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./public:/var/www/public
            - ./docker/supervisor/config:/etc/supervisor/conf.d
            - ./docker/supervisor/logs:/var/log/supervisor
        networks:
            - ${DOCKER_APP_NAME}

networks:
    site-builder:
        driver: bridge
